from datetime import datetime
from typing import Optional

from sqlalchemy import UniqueConstraint
from sqlmodel import SQLModel, Field, Relationship


class BrandBase(SQLModel):
    brand_name: str = Field(max_length=50, index=True)
    notes: Optional[str] = Field(default=None)
    organisation_id: Optional[int] = Field(default=None, foreign_key="organisation.organisation_id")


class Brand(BrandBase, table=True):
    __tablename__ = "brand"
    brand_id: Optional[int] = Field(default=None, primary_key=True)


    added_date: datetime = Field(default_factory=datetime.now)
    __table_args__ = (
        UniqueConstraint("brand_name", "organisation_id", name="uq_brand_name_organisation_id"),
    )

    buyables: "Buyable" = Relationship(back_populates="brand")
class BrandCreate(BrandBase):
    # exculdes brand id and added date as these are auto-generated by the DB - no user entry permitted
    pass

class BrandRead(BrandBase):
    brand_id: int
    added_date: datetime
