from datetime import datetime
from typing import Optional

from sqlalchemy import UniqueConstraint
from sqlmodel import SQLModel, Field, Relationship


class BrandBase(SQLModel):
    """
    Contains fields that are accessible to all models. i.e. fields that are not sensative,
    not system generated, and are user editable.
    """
    brand_name: str = Field(max_length=50, index=True)
    notes: Optional[str] = Field(default=None)
    organisation_id: Optional[int] = Field(default=None, foreign_key="organisation.organisation_id")


class Brand(BrandBase, table=True):
    """
    The table=True flag tells SQLModel to treat this class as a table in the database.
    """
    __tablename__ = "brand" # explicitlty set table name for the brand model
    # The primary key of of the table, set as optional to allow a Brand instance to be created without an ID
    # since this value is auto-generated by the database.
    brand_id: Optional[int] = Field(default=None, primary_key=True)
    # Note that the added date isn't in the create or base models - it's system generated and defaults to the current date and time
    added_date: datetime = Field(default_factory=datetime.now)
    # Unique constraint to ensure that a brand name is unique within an organisation.
    __table_args__ = (
        UniqueConstraint("brand_name", "organisation_id", name="uq_brand_name_organisation_id"),
    )
    # Define the relationship to the Buyable model. Including this definition means that SQLModel knows how to
    # interact with the Buyable model when working with Brand instances, and allows, for example, from the resulting
    # Brand instance to access the associated Buyable instances and all of its fields.
    buyables: "Buyable" = Relationship(back_populates="brand")


class BrandCreate(BrandBase):
    """
    Used in CREATE and PATCH endpoints to explicitly define the fields that can be passed to the API.
    It excludes brand id and added date as these are auto-generated by the DB - no user entry permitted.
    If a user were to pass in an ID they could inadvertently overwrite an existing record.
    If a user passed in an added_date they would overwrite the auto-generated date and render the data inaccurate.

    In this case, BrandCreate inherits from BrandBase and adds nothing; this is intentional to ensure that the
    same pattern is followed in all model files, making maintenance easier as the developer knows that CREATE and PATCH
    ALWAYS use the Create model.
    """
    pass

class BrandUpdate(SQLModel):
    """
    Organisation ID is excluded here as users are not permitted to change it - it's applied by the API by
    extracting the organisation ID from the User model received from the get_current_user dependency.
    """
    brand_name: Optional[str] = None
    notes: Optional[str] = None

class BrandRead(BrandBase):
    """
    Fields that may be returned to the use in a GET request, or as a response to a PATCH request.
    Includes all fields that are of interest to a user.  By inheriting from BrandBase (which is defined with only
    non-sensitive fields) we ensure that only safe fields are returned to the user.
    Here we are adding brand_id and added_date to the base model.
    """
    brand_id: int
    added_date: datetime
