import decimal
from typing import Optional

from pydantic import BaseModel
from sqlalchemy import UniqueConstraint
from sqlmodel import Field, SQLModel, Relationship

# These imports are needed for the Relationship forward references to work correctly
from app.models.currency import Currency
from app.models.image import Image
from app.models.organisation import Organisation


# Excludes system-generated fields like IDs and organisation_id.
class SupplierBase(SQLModel):
    supplier_name: str = Field(max_length=255)
    account_number: Optional[str] = Field(default=None, max_length=255)
    contact_person: Optional[str] = Field(default=None, max_length=255) # Increased max_length from 25
    phone_number: Optional[str] = Field(default=None, max_length=50)
    email_address: Optional[str] = Field(default=None, max_length=255)
    address: Optional[str] = Field(default=None, max_length=500)
    notes: Optional[str] = Field(default=None, max_length=2550)
    currency_code: str = Field(foreign_key="currency.currency_code", max_length=5)
    minimum_order_value: Optional[decimal.Decimal] = Field(
        default=None, max_digits=6, decimal_places=2
    )
    delivery_charge: Optional[decimal.Decimal] = Field(
        default=None, max_digits=6, decimal_places=2
    )


class Supplier(SupplierBase, table=True):
    # System-managed fields
    supplier_id: Optional[int] = Field(default=None, primary_key=True)
    organisation_id: int = Field(foreign_key="organisation.organisation_id")
    ## image_id not in base - can't upload an image until form has first been saved and supplier_id generated by DB
    image_id: Optional[int] = Field(default=None, nullable=True, foreign_key="image.image_id")
    # --- Relationships ---
    # These link to other tables but are not typically part of API request/response bodies.
    currency: Optional["Currency"] = Relationship()
    organisation: Optional["Organisation"] = Relationship()
    image: Optional["Image"] = Relationship()

    # --- Table Arguments ---
    # Define __table_args__ for the unique constraint - only one instance of supplier_name per org id
    __table_args__ = (
        UniqueConstraint("supplier_name", "organisation_id", name="UQ_supplier_name_organisation_id"),
    )

class SupplierCreate(SupplierBase):
    """
    Schema for creating a new supplier.
    Passes through SupplierBase but allows for future modifications without altering the base structure.
    """
    pass

class SupplierRead(SupplierBase):
    """
    Schema for reading a supplier's data from the API.
    Includes the database-generated supplier_id.
    """
    supplier_id: int


class SupplierUpdate(BaseModel):
    """
    Schema for updating an existing supplier.
    All fields are optional to support PATCH requests. Any fields not provided will not be changed.
    """
    supplier_name: Optional[str] = None
    account_number: Optional[str] = None
    contact_person: Optional[str] = None
    phone_number: Optional[str] = None
    email_address: Optional[str] = None
    address: Optional[str] = None
    notes: Optional[str] = None
    currency_code: Optional[str] = None
    minimum_order_value: Optional[decimal.Decimal] = None
    delivery_charge: Optional[decimal.Decimal] = None
    image_id: Optional[int] = None